config/routes.rb
OpenDataDay::Application.routes.draw do

  root 'messages#index'

  get "messages" => "messages#index"
  get "messages/create_user" => "messages#create_user"
  get "messages/get_data" => "messages#get_data"
  resource :message
end

app/models/message.rb
class Message < ActiveRecord::Base
  def self.columns
    @columns ||= []
  end
 
  def self.column(name, sql_type = nil, default = nil, null = true)
    columns << ActiveRecord::ConnectionAdapters::Column.new(name.to_s, default, sql_type.to_s, null)
  end
 
  # Manually define the columns used by this model
  column :content, :string

  attr_accessor :content
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index

  end

  def create
  	message = Hash.new
    message["content"] = params[:content]
    message["user"] = params[:user]
    PrivatePub.publish_to "/messages/new", :message => message
    render :nothing => true
  end

  def create_user
  	response = Hash.new
  	response["user"] = SecureRandom.uuid
  	respond_to do |format|
      format.json { render :json => response }
    end
  end

  def get_data
  	require 'open-uri'
	require 'json'

	result = JSON.parse(open("http://api.opendai.eu/api/KarlshamnPois/1.0/pois/Offentlig%20toalett").read)

	coordinates = Hash.new

	result.each_with_index do |dass, i|
		item = Hash.new
		item["long"] = dass["Locations"][0]["Main"]["Longitude"]
		item["lat"] = dass["Locations"][0]["Main"]["Latitude"]

		coordinates[i] = item
	end

	respond_to do |format|
      format.json { render :json => coordinates }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  <title>OpenDataDay</title>
  <meta name="viewport" content="width=device-width, initial-scale=1"> 
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  markers = handler.addMarkers(<%=raw @hash.to_json %>);
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBgHHPlsYf0e6VPwD_t4koqbJfq-EdWOiE&sensor=true"
  type="text/javascript"></script>
</head>
<body>


<div class="demo-wrapper" data-role="page">
        <!-- panel left -->
        <div class="panel left" data-role="panel" data-position="left" data-display="push" id="panel-01">
        	<div class="menu">
        		<ul>
        			<li><p>Chit Chat</p></li>
        			<li><%= link_to 'Start a chitty-chat', messages_path %></li>
        		</ul>
        	</div>

        </div>
		<div class="header" data-role="header">
			<span class="open left"><a href="#panel-01">&#x2630;</a></span>
            <span class="title">Chit-Chat</span>
			<span class="open right"><a href="#panel-02">&#x2605;</a></span>
		</div>
        <div class="content" data-role="content">
        <!-- body -->

        <%= yield %>

        </div>

    	<!-- panel right -->
    	<div class="panel right" data-role="panel" data-position="right" data-display="overlay" id="panel-02">

        <b>Credits</b>
        <p>App developed for Open data day 2014 @Bth</p>
    	</div>
	</div>
</body>
</html>

app/views/messages/index.html.erb
<div id="map-canvas" style='width: 100%; height: 400px;'></div>
<div id="chat">

</div>

<%= form_tag("", :class => "form-inline") do %>
	<%= text_field_tag :message, nil, :placeholder => "Write a message", :autocomplete => "off" %>
	<%= submit_tag("Send", :id => "chat-send") %>
<% end %>

<%= subscribe_to "/messages/new" %>